### ISSUE TITLE
parallel/queue download and display better error info

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#12]
I want to ask if the parallel/queue download feature can be implemented (having to input the url/id of tracks, albums, playlist in single line) and also possible better error info displaying in the cli if the input is wrong.
possibly like indicating the error and suggesting to view the help page foe more info on the format and such things.

#### CLI Example and present error
```
tiddl https://listen.tidal.com/track/288997277 https://listen.tidal.com/track/216149725 -q master -p "E:\" -o "{artist} - {title}"
usage: tiddl.exe [-h] [-o [FILE_TEMPLATE]] [-p [DOWNLOAD_PATH]] [-q [{low,normal,high,master}]] [-s]
                 [--no-skip] [--silent] [--verbose] [--no-color]
                 [input]
tiddl.exe: error: unrecognized arguments: https://listen.tidal.com/track/216149725
```

**Comment by oskvr37** [comment]
https://github.com/oskvr37/tiddl/commit/304fcc247980b97b3f19adc6f7171517076dc3c8

Let me know if this solution is fine!

**Comment by bachig26** [comment]
> [304fcc2](https://github.com/oskvr37/tiddl/commit/304fcc247980b97b3f19adc6f7171517076dc3c8)
> 
> Let me know if this solution is fine!

works awesome. thanks.

i just tried with tracks for now.
```
tiddl https://listen.tidal.com/track/288997277 https://listen.tidal.com/track/216149725
TIDDL Sunitha Sarathy - Engeyum Eppothum :: High Quality - 16 bit 44.1 kHz
Single URL ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% 27.82 / 27.82 MB
TIDDL track saved in E:\/Sunitha Sarathy - Engeyum Eppothum.flac
TIDDL BIBI - NABI :: High Quality - 16 bit 44.1 kHz
Single URL ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% 20.58 / 20.58 MB
TIDDL track saved in E:\/BIBI - NABI.flac
```
