### ISSUE TITLE
Track Covers

### ISSUE THREAD

**Issue by oskvr37** [oskvr37/tiddl#15]
Add option to download cover to the album directory and to tracks metadata.

**Comment by bachig26** [comment]
I thought of just commenting on the open issue instead, for the lacking metadata. if possible, please have look into the tags like `Recorded date` and `URL` to be included. this help in keep track of the download url and id personally.

the following is just an example for the metadata.

I downloaded the following track using this tool: [QobuzDownloaderX-MOD](https://github.com/DJDoubleD/QobuzDownloaderX-MOD)
[Sofia Carson - Come Back Home (From Purple Hearts Soundtrack Version).zip](https://github.com/user-attachments/files/16482909/Sofia.Carson.-.Come.Back.Home.From.Purple.Hearts.Soundtrack.Version.zip)
