### ISSUE TITLE
change config/log file path

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#17]
as you can see that i use cmder, and the tiddl config and log file is default in cmder folder.
i think the cmder always opens under its own directory `D:\cmder`, so when i installed tiddl, it might taken the path for these files.

if possible can you look into an option to define the path myself (as user), for example i want to change it to documents folder under c:\ or a folder `.tiddl` under `user\Roaming` folder.

#### SCREENSHOT

![explorer_PnG32Cm8GU](https://github.com/user-attachments/assets/a9eb487b-a721-4466-9cdb-0cf675bff748)

**Comment by oskvr37** [comment]
TIDDL opens config file in directory of command execution.

I will make it save config in users home directory as default, thanks for reporting issue!

**Comment by oskvr37** [comment]
https://github.com/oskvr37/tiddl/commit/67a288208067c3848e10712a3fb9f9939a9df3c6

If you want to change default path of the files, then you need to hardcode it in source code.
Other solution is to implement getting the path from os environment or to parse the path from cli args.

For now the default path is in users home directory. Please let me know what you think!

**Comment by bachig26** [comment]
> [67a2882](https://github.com/oskvr37/tiddl/commit/67a288208067c3848e10712a3fb9f9939a9df3c6)
> 
> If you want to change default path of the files, then you need to hardcode it in source code. Other solution is to implement getting the path from os environment or to parse the path from cli args.
> 
> For now the default path is in users home directory. Please let me know what you think!

i like this one. thanks.
