### ISSUE TITLE
improvements [album/playlist downloads]

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#19]
1. i'm seeing the error `TIDDL 'E:\\eNT/Christina Perri - trust.flac' is not a valid FLAC file`.

2. `56 URLs ■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□ 16% 0.00 / 0.00 MB`, the progress isn't clear.

3. **by default, the album/playlist should be under the folder of the album/playlist. but this is not created. it just downloads as singles/track.**

4. **furthermore if album/playlist is downloaded, by default it needs the track number. i think we can add a case condition to check the URL for track/album/playlist or a method of your convenience to make it work. (just a suggestion since i don't know much about it.)**

_***also it might be nice have some additions to show the difference to track/album/playlist downloads.**_

```
tiddl https://listen.tidal.com/album/76203980 -p "E:\eNT"
TIDDL sleeping for 2.5s
TIDDL Christina Perri - trust :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/Christina Perri - trust.flacB
TIDDL 'E:\\eNT/Christina Perri - trust.flac' is not a valid FLAC file
TIDDL sleeping for 2.9s
TIDDL Christina Perri - burning gold :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/Christina Perri - burning gold.flac
TIDDL 'E:\\eNT/Christina Perri - burning gold.flac' is not a valid FLAC file
TIDDL sleeping for 3.1s
TIDDL Christina Perri - be my forever (feat. ed sheeran) :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/Christina Perri - be my forever (feat. ed sheeran).flac
TIDDL 'E:\\eNT/Christina Perri - be my forever (feat. ed sheeran).flac' is not a valid FLAC file
TIDDL sleeping for 3.2s
TIDDL Christina Perri - human :: Max Quality - 24 bit 48.0 kHz
TIDDL track saved in E:\eNT/Christina Perri - human.flacB
TIDDL 'E:\\eNT/Christina Perri - human.flac' is not a valid FLAC file
TIDDL sleeping for 3.1s
TIDDL Christina Perri - one night :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/Christina Perri - one night.flac
TIDDL 'E:\\eNT/Christina Perri - one night.flac' is not a valid FLAC file
TIDDL sleeping for 3.3s
TIDDL Christina Perri - i dont wanna break :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/Christina Perri - i dont wanna break.flac
TIDDL 'E:\\eNT/Christina Perri - i dont wanna break.flac' is not a valid FLAC file
TIDDL sleeping for 3.4s
TIDDL Christina Perri - sea of lovers :: Max Quality - 24 bit 96.0 kHz
56 URLs ■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□ 16% 0.00 / 0.00 MB
```

**Comment by oskvr37** [comment]
1. https://github.com/oskvr37/tiddl/commit/28e7b00658dc4d56e0c1c0e9dd40e80f847e8070
2. There is existing TODO in code, to implement threaded download for fragmented tracks, it will be fixed
3. https://github.com/oskvr37/tiddl/commit/ae8603f8e160c8fe76672c9e28c49c5f331606fd let me know if it is what you meant!

>furthermore if album/playlist is downloaded, by default it needs the track number

I can't understand this one, please explain again

> *also it might be nice have some additions to show the difference to track/album/playlist downloads.

That's right, I'm planning to make it more clear what album/playlist/artist is downloaded at the time.

Thanks for reporting the issues! For next reports - please add issues separately, it will be easier to make commit like `fix #19`

**Comment by bachig26** [comment]
@oskvr37 
> 3. [ae8603f](https://github.com/oskvr37/tiddl/commit/ae8603f8e160c8fe76672c9e28c49c5f331606fd) let me know if it is what you meant!

no, with this file template, the songs are created like `Flowers.flac` under `Flowers` album folder under `Miley Cyrus` artist folder (`E:\Miley Cyrus\Flowers\Flowers.flac`). it's not right.
what i thought was like the below examples,
1. Track: should be same as before `Miley Cyrus - Flowers.flac` under download path.
2. Album: should be like, `{DOWNLOAD_PATH}\{ALBUM}\{Track no}. {Track}.flac`. example: `E:\head or heart\01. trust.flac`
3. Playlist: should be like, `{DOWNLOAD_PATH}\{PLAYLIST}\{Track no}. {Track}.flac`.

> > furthermore if album/playlist is downloaded, by default it needs the track number
> 
> I can't understand this one, please explain again
as example that made for album downloads above,
1. Album: should be like, `{DOWNLOAD_PATH}\{ALBUM}\{Track no}. {Track}.flac`. example: `E:\head or heart\01. trust.flac`
2. Playlist: should be like, `{DOWNLOAD_PATH}\{PLAYLIST}\{Track no}. {Track}.flac`.

> Thanks for reporting the issues! For next reports - please add issues separately, it will be easier to make commit like `fix #19`
sure, i'll do it separately from my next issue.

**Comment by oskvr37** [comment]
Alright, now I got you. I guess the solution is to create distinct templates.

Something like this in config file:
```
track_template: {artist}/{title}
album_template: {artist}/{album}/{title}
playlist_template: {playlist}/{title}
```

**Comment by bachig26** [comment]
> Alright, now I got you. I guess the solution is to create distinct templates.

yes, like this.
