### ISSUE TITLE
remove residual files when uninstalling

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#21]
the files like `tiddl.log` and `.tiddl_config.json` are left back after uninstalling the tiddl package.

maybe a message that these files might be left over can be added or if possible, a yes or no prompt can be provided to have it removed.

**Comment by oskvr37** [comment]
There is no way to create post uninstall script that would remove these files or show message that files are left.
I think the best solution is to leave the files here in case users would want to install package again and have their config remain in place.
