### ISSUE TITLE
just a q&a?

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#22]
project board?

**Comment by oskvr37** [comment]
There is ["Discussions"](https://github.com/oskvr37/tiddl/discussions) tab on GitHub.
At my day off from coding, I will prepare this repository for better community integration

**Comment by bachig26** [comment]
> There is ["Discussions"](https://github.com/oskvr37/tiddl/discussions) tab on GitHub. At my day off from coding, I will prepare this repository for better community integration

okay. thanks.
