### ISSUE TITLE
[threading] progess bar?

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#27]
can't see the progress bar with album and playlist downloads?

#### CLI OUTPUT:

```
tiddl https://listen.tidal.com/album/76203980 -p "E:\eNT"
TIDDL album: head or heart
TIDDL sleeping for 1.6s
TIDDL head or heart/trust :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/trust.m4a
TIDDL sleeping for 2.0s
TIDDL head or heart/burning gold :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/burning gold.m4a
TIDDL sleeping for 2.4s
TIDDL head or heart/be my forever (feat. ed sheeran) :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/be my forever (feat. ed sheeran).m4a
TIDDL sleeping for 1.8s
TIDDL head or heart/human :: Max Quality - 24 bit 48.0 kHz
TIDDL track saved in E:\eNT/head or heart/human.m4a
TIDDL sleeping for 1.9s
TIDDL head or heart/one night :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/one night.m4a
TIDDL sleeping for 2.1s
TIDDL head or heart/i dont wanna break :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/i dont wanna break.m4a
TIDDL sleeping for 2.4s
TIDDL head or heart/sea of lovers :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/sea of lovers.m4a
TIDDL sleeping for 2.5s
TIDDL head or heart/the words :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/the words.m4a
TIDDL sleeping for 1.8s
TIDDL head or heart/lonely child :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/lonely child.m4a
TIDDL sleeping for 2.5s
TIDDL head or heart/run :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/run.m4a
TIDDL sleeping for 1.5s
TIDDL head or heart/butterfly :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/butterfly.m4a
TIDDL sleeping for 1.9s
TIDDL head or heart/shot me in the heart :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/shot me in the heart.m4a
TIDDL sleeping for 2.3s
TIDDL head or heart/i believe :: Max Quality - 24 bit 96.0 kHz
TIDDL track saved in E:\eNT/head or heart/i believe.m4a
```

**Comment by oskvr37** [comment]
The issue comes from Max Quality tracks, where tracks are fragmented in urls.

I have not created progress bar for these tracks because we would have to make HEAD request to all urls (usually ~50 urls) to get track full size. But we can show the progress of urls list, instead of total size downloaded like it is when downloading single url.

**Comment by bachig26** [comment]
> I have not created progress bar for these tracks because we would have to make HEAD request to all urls (usually ~50 urls) to get track full size. But we can show the progress of urls list, instead of total size downloaded like it is when downloading single url.

also just thought of requesting (~50+) urls, will this case any issue with account block or something relevant?

**Comment by oskvr37** [comment]
Prolly Tidal has some limitations to api (429 http code) but it never happened to me when using this package.
I guess we can't ddos them with single computer and just 50 urls. It is like normal usage.
Track urls are at different server than Tidal api, I don't know if Tidal has systems to detect high usage but it possibly has.
Let's hope no one will get blocked using this package, I got to add a disclaimer to readme file.

**Comment by bachig26** [comment]
> Prolly Tidal has some limitations to api (429 http code) but it never happened to me when using this package. I guess we can't ddos them with single computer and just 50 urls. It is like normal usage. Track urls are at different server than Tidal api, I don't know if Tidal has systems to detect high usage but it possibly has. Let's hope no one will get blocked using this package, I got to add a disclaimer to readme file.

okay, thanks. also i thought in future when there are more features and other stuffs are added. then there could be an Wiki page unlocked for better and detailed description and steps and have the readme for general and legal (like disclaimer notes).
