### ISSUE TITLE
M4A to FLAC

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#28]
i just saw when i tried to test the v1.5.0 with album, it outputs as `.m4a`.

is it possible to get directly as `.flac` or add an conversion module, so the output results as `.flac`?

**Comment by oskvr37** [comment]
You can use [ffmpeg](https://www.ffmpeg.org/)

```
ffmpeg -i input.m4a output.flac
```

We can't get directly flac file for some tracks as they are fragmented in mp4 urls.
We must save them as m4a and then use audio conversion tools.

I will implement this feature but `ffmpeg` will be needed to run conversion.
