### ISSUE TITLE
download Low quality tracks Issue

### ISSUE THREAD

**Issue by pablo-reyes-cabrera** [oskvr37/tiddl#38]
Hi, when download a track in Low quality (what is a lossy format), ttidl convert it to Flac (and the size become x10)...

thanks for the code!

p.

**Comment by oskvr37** [comment]
Thanks for submitting issue!

I added cli argument *-e* to select file extension, you can now use `tiddl track_id -e flac` or `tiddl track_id -e mp3` to convert your downloaded tracks to desired extension. By default without the *-e* argument an extension wont be converted.

Check the [dev branch](https://github.com/oskvr37/tiddl/tree/dev) to test this feature!

**Comment by pablo-reyes-cabrera** [comment]
thanks!
