### ISSUE TITLE
tiddl does not retrieve master quality files

### ISSUE THREAD

**Issue by chris-ka1** [oskvr37/tiddl#39]
After I got my tidal authorisation (I have a master subscription) Iused the following command

tiddl https://listen.tidal.com/album/15361383 -q master

to get the master files of a recording I know and downloaded from tidal a year ago in master quality. 
tiddl only pulled high quality (16bit 44.1 kHz).

I know that the master files are 24bit

**Comment by oskvr37** [comment]
Did you make sure that the available quality on tidal is master?

**Comment by chris-ka1** [comment]
Yes. definitely. I just checked the link (https://listen.tidal.com/album/15361383 )again I mentioned in the issue. This album is playing at 96kHz 24Bit when I use the link above with my tidal master subscription.  When I go into terminal and type
tiddl https://listen.tidal.com/album/15361383 -q master
I get 44.1kHz 16bit

**Comment by oskvr37** [comment]
I dont know if we see the same website but there is only _HIGH_ quality, not _MASTER_.
![image](https://github.com/user-attachments/assets/d14be00e-9e41-423a-9446-f44d3da39e24)
