### ISSUE TITLE
Issue with name format and only downloading first 50 songs in playlist

### ISSUE THREAD

**Issue by JeffsGitHubAccount** [oskvr37/tiddl#44]
Hi there!

I've been having errors using the discontinued Tidal downloader and saw this successor exists which is awesome! Thank you for making this.

I am running into an issue with downloading my playlist where Tiddl is only downloading the first 50 songs in the playlist. If I try to start the download again it just detects the first 50 songs already exist and then ends. Perhaps large playlists aren't yet supported?

I'm also having a problem where Tiddl is not following the naming format specified by -o using the command, it's just using the track name as the file name. My command looks like this:
tiddl {my playlist} -p "D:\Music\Tiddl Downloads" -o "{artist} - {title}" -q master

I am using Tiddl version 1.8.0.

Thanks!

**Comment by oskvr37** [comment]
Thanks for submitting this issue!

Currently downloading more than 50 tracks is not implemented, I will be working on it.

The problem with -o arg is that it only works when single tracks are downloaded
```
# config
"track_template": "{artist}/{title}",
"album_template": "{artist}/{album}/{title}",
"playlist_template": "{playlist}/{title}",
```

```
# playlist downloading function
file_dir, file_name = downloadTrack(
  track,
  file_template=config["settings"]["playlist_template"],
  skip_existing=skip_existing,
  sleep=True,
  playlist=playlist["title"],
)
```

It will be fixed along with #40 issue.

**Comment by JeffsGitHubAccount** [comment]
Thank you for the response! I'm managed to get your change working and then went a step further.

I muddled my way through adding a new playlistNumber tag for file formatting to keep my songs organized by their place in the playlist, the standard {number} tag uses the song's track number in the album rather than the playlist.

To do that I changed the formatFilename function in utils.py to:

```
def formatFilename(template: str, track: Track, playlist="", playlist_number=None):
    artists = [artist["name"] for artist in track["artists"]]
    formatted_track: FormattedTrack = {
        "album": re.sub(r'[<>:"|?*/\\]', "_", track["album"]["title"].strip()),
        "artist": track["artist"]["name"].strip(),
        "artists": ", ".join(artists).strip(),
        "id": str(track["id"]).strip(),
        "title": track["title"].strip(),
        "number": str(track["trackNumber"]).strip(),
        "playlist": playlist.strip(),
        "playlistNumber": str(playlist_number) if playlist_number else "",
    }
```

Then in __init__.py I changed the downloadTrack function to receive and pass playlist_number. I don't know if the Tidal API supports track number for playlists, I use the playlist for loop track of how many tracks have been downloaded so far and pass that value to downloadTrack as they seem to be downloaded in order:

```
case "playlist":
                # TODO: add option to limit and set offset of playlist ✨
                playlist = api.getPlaylist(input_id)
                logger.info(f"playlist: {playlist['title']} ({playlist['url']})")

                playlist_cover = Cover(
                    playlist["squareImage"], 1080
                )  # playlists have 1080x1080 size

                playlist_items = api.getPlaylistItems(input_id)
                track_position = 1 # track position in playlist

                for item in playlist_items["items"]:
                    track = item["item"]

                    file_dir, file_name = downloadTrack(
                        track,
                        file_template=config["settings"]["playlist_template"],
                        skip_existing=skip_existing,
                        sleep=True,
                        playlist=playlist["title"],
                        playlist_number=track_position,
                    )

                    track_position += 1

                    if SAVE_COVER:
                        playlist_cover.save(f"{download_path}/{file_dir}")

                continue
```

That worked great as far as I can tell and I'm now very happy with the name formatting.

![image](https://github.com/user-attachments/assets/003762ae-79c5-406c-96fb-b1f52ca0e633)

**Comment by oskvr37** [comment]
Now `tiddl 'playlist' -o "{playlist_number}. {artist} - {title}"` works fine
