### ISSUE TITLE
Feature request: Download all tracks from user favorite tracks

### ISSUE THREAD

**Issue by JeffWDH** [oskvr37/tiddl#48]
It would be nice to be able to download all tracks from a user's favorite (hearted) tracks without putting them in a playlist first.

**Comment by oskvr37** [comment]
It is already planned in https://github.com/oskvr37/tiddl/issues/35, user library will be synchronized, there will be option to choose what to synchronize - tracks, artists, albums, playlists

**Comment by oskvr37** [comment]
[Release notes of v3.0.0](https://github.com/oskvr37/tiddl/releases/tag/v3.0.0)

> Currently only `url` subcommand is available with `download` command

**Comment by cstaelen** [comment]
Thanks for your answer, I read the release notes, but I thought maybe there was a trick for favs :)

**Comment by cstaelen** [comment]
Should I create new feature request for that ?
