### ISSUE TITLE
Prevent M4A files

### ISSUE THREAD

**Issue by jjdenhertog** [oskvr37/tiddl#52]
Hello 👋 

I'm using Tiddl to download files at the highest possible output. I have set the preference to "HI_RES_LOSSLESS". But I notice it starts downloading a lot of M4A files. Those files don't playwell on some devices. How can I make sure that it preferes FLAC over M4A? 

Cheers,
Jaap

**Comment by oskvr37** [comment]
Hey, make sure every track you download are available in high or master quality on Tidal (as only high and master qualities are downloaded in flac) and if so then please use `--verbose` option and paste here the output of terminal.
If you want to convert tracks below high quality to flac, then set extension to flac with `-e flac` option!

**Comment by jjdenhertog** [comment]
The track that I'm finding this with is this one
https://tidal.com/browse/track/152989975

Below the output.

`[ TIDDL ] main Namespace(input=['https://tidal.com/browse/track/152989975'], file_template=None, download_path=None, file_extension=None, quality=None, include_singles=False, save_options=False, input_file='', no_skip=False, silent=False, verbose=True, no_color=False)
[ Config ] __init__ loaded {'download_path': './', 'track_quality': 'HI_RES_LOSSLESS', 'track_template': '{number} - {artist} - {title}', 'album_template': '{artist}/{album}/{number} - {artist} - {title}', 'playlist_template': 'Playlists/{PlaylistName}', 'file_extension': ''}
[ Config ] update updating
[ Config ] _save {'download_path': './', 'track_quality': 'HI_RES_LOSSLESS', 'track_template': '{number} - {artist} - {title}', 'album_template': '{artist}/{album}/{number} - {artist} - {title}', 'playlist_template': 'Playlists/{PlaylistName}', 'file_extension': ''}
[ Config ] update updated
[ TIDDL ] main token expires in 4 days
[ TidalApi ] _request tracks/152989975 {'countryCode': 'NL'}
[ TidalApi ] _request tracks/152989975/playbackinfo {'audioquality': 'HI_RES_LOSSLESS', 'playbackmode': 'STREAM', 'assetpresentation': 'FULL'}
[ TIDDL ] 15 - Igor Levit - 6 Chorale Preludes, BV B 50_ Herzlich tut mich verlangen, Op. 122_10 :: Max Quality - 24 bit 96.0 kHz
[ download ] downloadTrackStream mime_type: application/dash+xml
[ download ] downloadTrackStream codecs: flac
threaded download ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100%
[ download ] downloadTrackStream ('.//', '15 - Igor Levit - 6 Chorale Preludes, BV B 50_ Herzlich tut mich verlangen, Op. 122_10')
[ download ] __init__ ('7690ffdb-37bb-42f9-84c3-49513a4ca123', 'https://resources.tidal.com/images/7690ffdb/37bb/42f9/84c3/49513a4ca123/1280x1280.jpg')
[ download ] get got cover
[ TIDDL ] track saved as .///15 - Igor Levit - 6 Chorale Preludes, BV B 50_ Herzlich tut mich verlangen, Op. 122_10.m4a`

In Tidal it is mentioned as "MAX" but I would be expecting FLACs in that case.

**Comment by oskvr37** [comment]
The issue is that high quality tracks on Tidal are fragmented with mp4 extension and we need to save them as m4a file.
When we save the file as flac we get the `mutagen.flac.FLACNoHeaderError` exception.
This is solved by downloading tracks as m4a and then we convert them with ffmpeg to flac so we can set metadata.
I think that there is better solution to this problem but we probably need more knowledge about audio extensions or just to test different solutions.

**Comment by jjdenhertog** [comment]
@oskvr37 It was not working for me because I needed to install `libvmaf`. The error I got when running ffmpeg was this: 
```
dyld[82984]: Library not loaded: @loader_path/../../../../opt/libvmaf/lib/libvmaf.1.dylib
  Referenced from: <D796CA17-8AEC-3511-B728-89EC20948570> /usr/local/Cellar/ffmpeg/6.0_1/bin/ffmpeg
  Reason: tried: '/usr/local/Cellar/ffmpeg/6.0_1/bin/../../../../opt/libvmaf/lib/libvmaf.1.dylib' (no such file), '/usr/local/lib/libvmaf.1.dylib' (no such file), '/usr/lib/libvmaf.1.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

But that did not come through while running the Tiddl command. Because it simply said 'None'.

**Comment by papavlos** [comment]
My workaround is a simple bash script converting all m4a files into flac, run in the download dir after each download.
```
#!/bin/bash
for f in *.m4a; do ffmpeg -i "$f" -f flac "${f%.m4a}.flac"; done
rm *.m4a
```

**Comment by teddybee-r** [comment]
```bash
find . -type f -name "*.m4a" -print0 | xargs -0 -I "{}" bash -c 'ffmpeg -i "$1" -c:a flac "${1%.m4a}.flac" && rm "$1"' _ "{}"
```
This is a bit better as it scans all all the sub folders in your current working directory.

**Comment by papavlos** [comment]
@teddybee-r Yes, you're right. Your version is superior :ok_hand: :smiley: 
Essential poetry... Isn't it?...

**Comment by PatrykMis** [comment]
@teddybee-r I would slightly refine it to avoid trying to transcode by ffpeg:

```bash
find . -type f -name "*.m4a" -print0 | xargs -0 -I "{}" bash -c 'ffmpeg -i "$1" -c:a copy "${1%.m4a}.flac" && rm "$1"' _ "{}"
```

Note that you still have unnessesary tags like `encoder`, `major_brand`, `minor_version` and `compatible_brands` in your resulting FLAC file then.

**Comment by teddybee-r** [comment]
I have never looked at the source I just had issues with m4a in jellyfin. I don't know if everything is 100% flac so I just let it do its thing. The only difference was 0.1MB extra in the flac and I guess that are the extra tags - it is so fast that I did not mind it trying to transcode.

I use Picard for tagging albums. So I don't mind. 
https://picard.musicbrainz.org/
