### ISSUE TITLE
KeyError: 'audioQuality'

### ISSUE THREAD

**Issue by papavlos** [oskvr37/tiddl#54]
Since two or three days there is the following problem:
```
Traceback (most recent call last):
  File "---/bin/tiddl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "---/lib/python3.12/site-packages/tiddl/__init__.py", line 256, in main
    downloadAlbum(input_id, skip_existing)
  File "---/lib/python3.12/site-packages/tiddl/__init__.py", line 213, in downloadAlbum
    file_dir, file_name = downloadTrack(
                          ^^^^^^^^^^^^^^
  File "---/lib/python3.12/site-packages/tiddl/__init__.py", line 162, in downloadTrack
    quality = TRACK_QUALITY[stream["audioQuality"]]
                            ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'audioQuality'
```
I have only masked my actual installation path by `---`.
Apparently they must have changed something in their API.

**Comment by energy-sync** [comment]
I have this happen for every 15-30 songs. It seems I can just restart the script and it'll work again

**Comment by oskvr37** [comment]
Thanks for adding this issue!
Please provide me the IDs of songs or albums that cause the problem

**Comment by papavlos** [comment]
For me it happens for any album, including the album/284165608.

My install details: 
- Arch linux, always updated
- `tiddl` installed and run in a dedicated Python Virtual Environment

**Comment by papavlos** [comment]
**<ins>Update</ins>**
I have noticed very fresh update of `tiddl` so decided to create also a fresh `venv`.
Have activated it and installed `tiddl` together with `requests` and `mutagen`.
No problems now, at least with 'album/284165608'.
So it must have been something in my previous install. 
So sorry for bothering you. For closing.
