### ISSUE TITLE
Video and metadata issues.

### ISSUE THREAD

**Issue by teddybee-r** [oskvr37/tiddl#59]
Hey!

Some albums have a single video in them and crashes the download.
A way to handle and ignore videos would be nice. I've tried a few modifications but I'm not a python guy.
Example: (album containing only videos) album/97129869

Another issue I've ran into multiple times is incorrect metadata.
Tracks completely ignoring the (Artist Remix) at the end of the title.
Example: album/13206400

Another question I have: What is the logical order of downloads in a .txt file. It does not go from top to bottom it looks completely random to me.

**Comment by oskvr37** [comment]
Hey, videos are now skipped and i have added option to add `version` of the track to the file formatting like so: `"track_template": "{artist}/{title} ({version})"`.
Track versions were skipped as they don't belong to the track title, they belong to `version` variable of `Track`
