### ISSUE TITLE
default output filename

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#6]
currently, the filename is just the song name.
with `-o` argument, user can make change to it, but i want to ask if you could add options to have few presets like `{artist} - {track}.flac`.

**Comment by oskvr37** [comment]
Hey, I added this feature, you can test if it's working properly.

Use -o with `{id} {title} {number} {artist} {album} {artists}` variables
I'm planning to add presets to download path too, or just make `{artist}/{album}/{title}` argument create new directory.

**Comment by bachig26** [comment]
> Hey, I added this feature, you can test if it's working properly.
> 
> Use -o with `{id} {title} {number} {artist} {album} {artists}` variables

hi, i just tried and it works fine.
