### ISSUE TITLE
if track["streamStartDate"] is None, strptime() will fail

### ISSUE THREAD

**Issue by emilyinspace** [oskvr37/tiddl#63]
I stumbled upon this problem on the title as part of checking out [this](https://listen.tidal.com/playlist/5ed2512d-b27b-4d0c-845d-3fd517401af2) playlist.

My thought was to change the line below and use Epoch time. 

https://github.com/oskvr37/tiddl/blob/2ba6c9b9767da4eac7188029a592d1556eb94e4c/tiddl/utils.py#L81

with 

`        track["streamStartDate"] if track["streamStartDate"] is not None else "1970-01-01", "%Y-%m-%dT%H:%M:%S.000+0000"
`

**Comment by oskvr37** [comment]
Thanks for this issue!
Now, if `streamStartDate` is missing, it will be replaced with Epoch time
